### ISSUE TITLE
Clear Cart Upon Checkout and Return to Login Screen

### ISSUE THREAD

**Issue by tmajchrz** [tmajchrz/FED_2019#18]
After the user checks out, clear the cart, so the items they selected no longer display on the page, display a quote about food security, etc. which times out after one minute, and then return to the login screen.  It might make sense to have a table in the database with quotes which could be selected at random.  For now, you could just display the same one every time.

See the prototype to see how this should work.  
https://xd.adobe.com/view/e9bc8409-ba6a-4994-45df-ce3a41ba1a4f-9f8d/screen/48cb5be2-603f-4ef7-8f85-208655186e7e/Web-1920-10?fullscreen

**Comment by DaveBabler** [comment]
This issue has been resolved and will be reflected in today's pull request.
