### ISSUE TITLE
Local Database Remembers

### ISSUE THREAD

**Issue by tmajchrz** [tmajchrz/FED_2019#9]
The local database does not remember items stocked in the past, requiring an external look up again for repeat items which were depleted from stock.

**Comment by DaveBabler** [comment]
Question. on this...zeroing out a product totally purges it from the database?!  That....that's not how databases are supposed to work.  Is there code in there that is purposefully causing this?

**Comment by tmajchrz** [comment]
I agree this seems not to be ideal, and I assume there is code creating this circumstance, which we may wish to change....

**Comment by DaveBabler** [comment]
This is no longer an issue. 
Please see the #soldout tag in slack for an update on this.
